name: Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build Docker image
      run: docker build -t nguyenquang0601/node-hello-app:${{ github.run_number }} -f Dockerfile .

    - name: Push Docker image to Docker Hub
      run: docker push nguyenquang0601/node-hello-app:${{ github.run_number }} 
  
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: changing the deployment of git repo
        with:
          repository: 'nnguyenquangg/argocd-deployment'
          token: ${{ secrets.GIT_TOKEN }}
          ref: 'main'
      - name: modify the image
        run: |
          git config user.email nguyenquang06012000@gmail.com
          git config user.name nnguyenquangg
          pwd
          cd node-application
          cat deployment.yaml
          pwd
          sed -i "s+nguyenquang0601/node-hello-app.*+nguyenquang0601/node-hello-app:$RUN_NUMBER+g" deployment.yaml
          cat deployment.yaml
          cd ..
          git add .
          git commit -m 'Done  by Github Actions   Job changemanifest: ${{ github.run_number }}'
          git push origin main
        env:
          GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
          GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}
          RUN_NUMBER: ${{ github.run_number }}