name: Get Kubernetes Namespace

on:
  push:
    branches:
      - main

jobs:
  get_namespace:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # - name: Set up kubectl
    #   uses: azure/setup-kubectl@v3
    #   with:
    #     version: latest

    # - name: Authenticate with kubeconfig
    #   run: |
    #     mkdir -p ~/.kube
    #     cp .github/config  ~/.kube/config

    # - name: Get namespaces
    #   run: |
    #     kubectl get namespaces

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build Docker image
      run: docker build -t nguyenquang0601/node-hello-app:${{ github.run_number }} -f Dockerfile .

    - name: Push Docker image to Docker Hub
      run: docker push nguyenquang0601/node-hello-app:${{ github.run_number }} 